# Generated by Django 3.2.7 on 2021-11-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0010_auto_20211103_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='DocsEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Archivo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('firma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.tipodoc', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Documento de empresa',
                'verbose_name_plural': 'Documentos de empresa',
            },
        ),
        migrations.CreateModel(
            name='DocsEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Archivo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado', verbose_name='Empleado')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.tipodoc', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Documento de empleado',
                'verbose_name_plural': 'Documentos de empleado',
            },
        ),
    ]
