# Generated by Django 3.2.7 on 2021-11-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsempleado',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Documento'),
        ),
    ]
