# Generated by Django 3.2.7 on 2021-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_docsempleado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodoc',
            name='nombre',
            field=models.CharField(default='Initial', max_length=100, verbose_name='Nombre'),
        ),
    ]
