# Generated by Django 3.2.7 on 2021-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_alter_tipodoc_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodoc',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
