# Generated by Django 3.2.7 on 2021-11-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleado_options'),
        ('documentacion', '0006_alter_docsempresa_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado', verbose_name='Empleado'),
        ),
    ]
