# Generated by Django 3.2.7 on 2021-11-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_carne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
