# Generated by Django 3.2.7 on 2021-10-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('primer_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.login', verbose_name='Código Login')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol', verbose_name='Código Rol')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol', verbose_name='Rol'),
        ),
    ]
