# Generated by Django 3.2.7 on 2021-10-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0002_auto_20211026_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.CharField(max_length=50, verbose_name='Areas')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('responsabilidades', models.TextField(verbose_name='Responsabilidades')),
                ('area_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite', models.CharField(max_length=50, verbose_name='Comité')),
            ],
            options={
                'verbose_name': 'comite',
                'verbose_name_plural': 'comites',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1_emp', models.CharField(max_length=12, verbose_name='Primer Nombre')),
                ('nombre2_emp', models.CharField(max_length=12, verbose_name='Segundo Nombre')),
                ('apellido1_emp', models.CharField(max_length=12, verbose_name='Primer Apellido')),
                ('apellido2_emp', models.CharField(max_length=12, verbose_name='Segundo Apellido')),
                ('cedula_emp', models.BigIntegerField(verbose_name='Cédula')),
                ('telefono_emp', models.CharField(blank=True, max_length=10, verbose_name='Teléfono')),
                ('celular_emp', models.CharField(max_length=10, verbose_name='Celular')),
                ('direccion_emp', models.CharField(max_length=50, verbose_name='Dirección')),
                ('nivel_emp', models.CharField(choices=[('Básica', 'Educación Básica'), ('Bachiller', 'Educación Media'), ('Profesional', 'Educación Superior')], max_length=12, verbose_name='Nivel de Educación')),
                ('cargo_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'empleados',
                'verbose_name_plural': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'credencial',
                'verbose_name_plural': 'credenciales',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre Rol')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('comite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.comite', verbose_name='Id Comité')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSGSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado', verbose_name='Código Empleado')),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.login', verbose_name='Código Login')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol', verbose_name='Código Rol')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='DocumentacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=50, verbose_name='Nombre Documentación')),
                ('path_doc', models.CharField(max_length=100, verbose_name='Ruta Documento')),
                ('fecha_mod', models.DateField(auto_now=True)),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado', verbose_name='Id Empleado')),
            ],
            options={
                'verbose_name': 'docuempleado',
                'verbose_name_plural': 'docuempleados',
            },
        ),
    ]
