# Generated by Django 3.2.7 on 2021-10-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_area_cargo_comite_documentacionempleado_empleado_login_rol_usuariosgsst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='comite_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.comite', verbose_name='Id Comité'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Encar', 'Encargado del SG-SST'), ('Presi', 'Presidente Comité'), ('Secre', 'Secretario Comité')], max_length=50, verbose_name='Nombre Rol'),
        ),
    ]
