# Generated by Django 3.2.7 on 2021-10-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20211026_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.cargo', verbose_name='Cargo'),
        ),
    ]
