# Generated by Django 3.2.7 on 2021-10-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_empleado_cargo_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosgsst',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado', verbose_name='Nombre Empleado'),
        ),
        migrations.AlterField(
            model_name='usuariosgsst',
            name='id_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.login', verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuariosgsst',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol', verbose_name='Rol'),
        ),
    ]
