# Generated by Django 3.2.7 on 2021-10-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20211026_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosgsst',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='usuariosgsst',
            name='id_login',
        ),
        migrations.RemoveField(
            model_name='usuariosgsst',
            name='id_rol',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='UsuarioSGSST',
        ),
    ]
