# Generated by Django 3.2.7 on 2021-10-27 00:48

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Usuarios', '0007_auto_20211026_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
            ],
            options={
                'verbose_name': 'credencial',
                'verbose_name_plural': 'credenciales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.CreateModel(
            name='UsuarioSGSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado', verbose_name='Nombre Empleado')),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.login', verbose_name='Nombre de Usuario')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
