# Generated by Django 3.2.7 on 2021-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_auto_20211026_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Encar', 'Encargado del SG-SST'), ('Pres1', 'Presidente Comité COCOLA'), ('Pres2', 'Presidente Comité COPASST'), ('Pres3', 'Secretario Comité BE')], max_length=50, verbose_name='Nombre Rol'),
        ),
    ]
