# Generated by Django 3.2.7 on 2021-11-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_carne'),
        ('Usuarios', '0010_auto_20211103_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosgsst',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado', verbose_name='Nombre Empleado'),
        ),
    ]
